server:
  port: 7777
dubbo:
  application:
    name: dubbo-comsumer
    qosEnable: true
    qosAcceptForeignIp: true
  registry:
    address: zookeeper://47.106.238.98:2181
  service:
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20882
