server:
  port: 7777
dubbo:
  application:
    name: dubbo-comsumer
    qosEnable: true
    qosAcceptForeignIp: true
  registry:
    address: nacos://11.239.163.65:8848
  service:
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20882
